# Alpaca API credentials for WhisperChart
# Get your free API keys from: https://app.alpaca.markets/
# Note: Live trading requires a funded account, but market data works with paper trading account

ALPACA_API_KEY = "yPKSHU40NDQRYQPFK8DHE"
ALPACA_SECRET_KEY = "eXWj2sPwjt0vEKk6143pVO1paRSXzv30e7PtnAbO"

# Replace "your_alpaca_secret_key_here" with your actual secret key from Alpaca
