name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install lint tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.5.0 black==24.4.2

      - name: Ruff check
        run: ruff check .

      - name: Black check
        run: black --check .

